apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeserver-argo-application
  namespace: argocd
  labels:
    app.kubernetes.io/name: homeserver
    app.kubernetes.io/part-of: homeserver-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/maxfelius/homeArgoCDApplication.git
    targetRevision: main
    path: applications

  destination:
    server: https://kubernetes.default.svc
    namespace: homeserver

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
